### ISSUE TITLE
Fix: estate data format

### ISSUE THREAD

**Issue by kkx7787** [Hanaro-OMNM/Hanasset-FE#120]
## Description
- 크롤링 데이터 포맷 변경에 따른 웹 매물 데이터 연동

## Estimated Duration

12/04(수) ~ 12/05(목) [2일]

## Classification

- [x] 기능
- [ ] 버그
- [ ] 기타

## TO-DO

- [ ] 매물 리스트 페이지 새로운 더미 데이터 포맷 연동
- [ ] 매물 상세 페이지 새로운 더미 데이터 포맷 연동
- [ ] 매물 즐겨찾기 기능 구현
