### ISSUE TITLE
Fix: enhance UX

### ISSUE THREAD

**Issue by kkx7787** [Hanaro-OMNM/Hanasset-FE#148]
## Description

- 사용자 경험 측면 발생되는 이슈 수정

## Estimated Duration

12/28(토) ~ 12/28 (토) [1일]

## Classification

- [ ] 기능
- [x] 버그
- [ ] 기타

## TO-DO

- [x] 관심 지역 이동했을 때 마커 API 요청 안되는 이슈 수정
- [x] 네이버 지도 UI가 아닌 컴포넌트 드래그 API 요청 이슈 수정
- [x] 대출 추천 페이지 관심 매물 등록/삭제 버튼 UI 수정
