### ISSUE TITLE
Feat main page contents

### ISSUE THREAD

**Issue by yje9802** [Hanaro-OMNM/Hanasset-FE#39]
## Description

메인 페이지에서 보여주는 두 가지 컨텐츠 구현
- 주소로 골라보기
- 카테고리 별 골라보기

## Estimated Duration

10/28(월) ~ 10/28(월) [1일]

## Classification

- [x] 기능
- [ ] 버그
- [ ] 기타

## TO-DO

- [ ] 주소로 골라보기 구현
  - [ ] 지역 필터 컴포넌트 구현
- [ ] 카테고리 별 골라보기 구현
