### ISSUE TITLE
Feat: mypage add asset record

### ISSUE THREAD

**Issue by mkngkm** [Hanaro-OMNM/Hanasset-FE#64]
## Description

- 마이홈에 있는 상담 내역삭제 후 내자산 내역 추가
- 직업, 연소득, 부동산자산, 대출내역
- property form과 연결 예정 -> 마이홈에서 수정 가능

## Estimated Duration

10/30(수) ~ 10/31 (목) [2일]

## Classification

- [ ] 기능
- [ ] 버그
- [ ] 기타

## TO-DO

- [ ] 마이홈 상담 내역 삭제
- [ ] 마이홈에 내자산 내역 추가
- [ ] property form으로 라우팅
