### ISSUE TITLE
Refactor: consulting css

### ISSUE THREAD

**Issue by mkngkm** [Hanaro-OMNM/Hanasset-FE#78]
## Description

- consulting tab css 수정
- consulting reservation page css 수정
- chat css 수정

## Estimated Duration

11/3(일) ~ 11/4 (월) [2일]

## Classification

- [ ] 기능
- [ ] 버그
- [ ] 기타

## TO-DO

- [ ] consulting tab css 수정
- [ ] consulting reservation page css 수정
- [ ] chat css 수정
