### ISSUE TITLE
Feat: my estate list

### ISSUE THREAD

**Issue by Choeseonjeong** [Hanaro-OMNM/Hanasset-FE#98]
## Description
내 관심 매물 페이지 제거하고, my-estate-list 추가

## Estimated Duration

11/18 (월) ~ 11/18 (월) [1일]

## Classification

- [x] 기능
- [ ] 버그
- [ ] 기타

## TO-DO

- [x] 내 관심 매물 페이지 제거
- [x] navBar, Edit 이미지 제거
- [x] my-estate-list 추가
- [x] 내 관심 매물 꾸밈
